[package]
edition = "2021"
name = "dojo-c"
version = "0.1.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dojo-types = { git = "https://github.com/Larkooo/dojo", branch = "torii-libp2p"}
torii-client = { git = "https://github.com/Larkooo/dojo", branch = "torii-libp2p" }
torii-grpc = { git = "https://github.com/Larkooo/dojo", branch = "torii-libp2p", features = [
    "client",
] }

parking_lot = "0.12.1"
starknet = "0.8.0"
starknet-crypto = "0.6.0"
tokio = { version = "1.32.0", default-features = false, features = ["rt"] }
url = "2.5.0"
anyhow = "1.0.76"
serde = { version = "1.0.193", features = ["derive"] }
tokio-stream = "0.1.14"
futures = "0.3.30"
futures-channel = "0.3.30"

# WASM
# [target.'cfg(target_arch = "wasm32")'.dependencies]
serde-wasm-bindgen = "0.6.3"
wasm-bindgen = "0.2.89"
wasm-bindgen-futures = "0.4.39"
tsify = "0.4.5"
serde_json = "1.0.111"
js-sys = "0.3.66"
web-sys = { version = "0.3.4", features = [
    'MessageEvent',
    'Window',
    'Worker',
    'WorkerGlobalScope',
    'console',
] }

[build-dependencies]
cbindgen = "0.26.0"
