[package]
edition = "2021"
name = "dojo-c"
version = "1.0.0"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
dojo-types = { git = "https://github.com/dojoengine/dojo" }
torii-client = { git = "https://github.com/dojoengine/dojo" }
torii-grpc = { git = "https://github.com/dojoengine/dojo", features = [
    "client",
] }
torii-relay = { git = "https://github.com/dojoengine/dojo" }

parking_lot = "0.12.1"
starknet = "0.9.0"
starknet-crypto = "0.6.1"
tokio = { version = "1.32.0", default-features = false, features = ["rt"] }
url = "2.5.0"
anyhow = "1.0.76"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.115"
tokio-stream = "0.1.14"
futures = "0.3.30"
futures-channel = "0.3.30"
wasm-bindgen = "0.2.92"

[patch.crates-io]
deno_task_shell = { git = "https://github.com/denoland/deno_task_shell", tag = "0.15.0" }

# WASM
[target.'cfg(target_arch = "wasm32")'.dependencies]
serde-wasm-bindgen = "0.6.3"
wasm-bindgen-futures = "0.4.39"
tsify = "0.4.5"
serde_json = "1.0.111"
js-sys = "0.3.66"
web-sys = { version = "0.3.4", features = [
    'MessageEvent',
    'Window',
    'Worker',
    'WorkerGlobalScope',
    'console',
] }
crypto-bigint = "0.5.5"

[build-dependencies]
cbindgen = "0.26.0"
